Add typing utils module
wazo-platform/xivo-lib-python pull request #151
Opened 2024-09-20 19:38 UTC by DrPyser

- JSON typing alias

2024-09-20 20:29 UTC, pc-m requested changes

2024-09-20 20:29 UTC, pc-m commented on debian/control
> +         python3-typing-extensions
missing a comma here. `python3-yaml,`

2024-09-20 20:29 UTC, pc-m commented on xivo/tests/test_typing_utils.py
> +# from typing import get_type_hints
I think this line should be replace with this ;)
```
# Copyright 2024 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later
```

2024-09-23 11:58 UTC, fblackburn1 commented on xivo/tests/test_typing_utils.py
> +# Copyright 2014-2024 The Wazo Authors  (see the AUTHORS file)
why 2014?

2024-09-30 14:24 UTC, DrPyser commented
> Added `mergeit` label in the release process But I don't approve this PR The usage (for now) is only in python client which should never depend of this library (even only for typing)

We already discussed this previously, sorry that wasn't understood then.

Why is it bad for the clients to depend on xivo-lib-python?

I suppose we should duplicate this module in wazo-lib-rest-client for usage in wazo python clients?

2024-09-30 17:12 UTC, fblackburn1 commented
> Why is it bad for the clients to depend on xivo-lib-python?

xivo-lib-python is intended to be a server library, not to be installed outside of the server. We don't want to block ourself/packaging because we add a dependency on wazo python clients (ex: build debian based on requirements.txt, or move requirements.txt to setup.py/pyproject.toml)

Rule of thumb about lib-python, when it doesn't make sense or if the code is huge, make a separate module. IMHO we are in the first scenario

> 
> I suppose we should duplicate this module in wazo-lib-rest-client for usage in wazo python clients?

Yes it's the easier solution (and probably the one that is worth it)
Another solution for this specific library, is to make a generic typing library + debian packaging (if the python library already exist, then it's to make debian packaging). To be determined if it worth it ...

2025-02-19 14:11 UTC, closed without merging